#!/bin/bash
# Claude Bridge CLI — zero-dependency alternative to justfile
# Generated by setup.sh with server-specific values
# Usage: ./bridge.sh <command> [args]

# --- Config (filled by setup.sh) ---
SSH_TARGET="{{TARGET}}"
SSH_PORT="{{PORT}}"
SSH_KEY="{{KEY}}"
BRIDGE="{{BRIDGE}}"
# --- End Config ---

SSH="ssh -p $SSH_PORT -i $SSH_KEY $SSH_TARGET"

usage() {
    cat << 'EOF'
Claude Bridge CLI

Usage: ./bridge.sh <command> [args]

Commands:
  ask <prompt>         Ask remote Claude and wait for response (synchronous)
  ask -c <prompt>      Ask with session continuity (follow-up)
  send <prompt>        Queue a task (async, needs process/worker)
  follow-up <prompt>   Queue a follow-up task (async, continues session)
  process              Process all pending tasks once
  results              Show all completed results
  read <task-id>       Read a specific result
  clear                Clear all results
  pull <remote> <local>  Download file from remote server
  push <local> <remote>  Upload file to remote server
  worker-start         Start background worker
  worker-stop          Stop background worker
  worker-status        Check worker and queue status
  ssh <cmd>            Run any command on remote
  help                 Show this help
EOF
}

case "${1:-help}" in
    ask)
        shift
        CONTINUE_FLAG=""
        if [ "$1" = "-c" ]; then
            CONTINUE_FLAG="--continue"
            shift
        fi
        [ -z "$1" ] && echo "Usage: ./bridge.sh ask [-c] <prompt>" && exit 1
        ALLOWED_TOOLS="Bash(ls:*) Bash(cat:*) Bash(df:*) Bash(ps:*) Bash(docker:*) Bash(systemctl:*) Bash(uname:*) Bash(hostname:*) Bash(uptime:*) Bash(free:*) Bash(head:*) Bash(tail:*) Bash(wc:*) Bash(grep:*) Bash(find:*) Read Write Edit Glob Grep"
        $SSH "export PATH=\$HOME/.local/bin:\$HOME/.npm-global/bin:\$PATH && cd \$HOME/claude-workspace && claude -p '$1' --allowedTools '$ALLOWED_TOOLS' -n claude-bridge $CONTINUE_FLAG"
        ;;
    send)
        [ -z "$2" ] && echo "Usage: ./bridge.sh send <prompt>" && exit 1
        $SSH "python3 $BRIDGE/submit_task.py '$2'"
        ;;
    follow-up|followup)
        [ -z "$2" ] && echo "Usage: ./bridge.sh follow-up <prompt>" && exit 1
        $SSH "python3 $BRIDGE/submit_task.py '$2' --continue"
        ;;
    process)
        $SSH "export PATH=\$HOME/.local/bin:\$HOME/.npm-global/bin:\$PATH && python3 $BRIDGE/process_tasks.py"
        ;;
    results)
        $SSH "for f in $BRIDGE/outbox/*.json; do [ -f \"\$f\" ] && echo \"=== \$(basename \$f) ===\" && cat \"\$f\" && echo; done 2>/dev/null || echo 'No results yet.'"
        ;;
    read)
        [ -z "$2" ] && echo "Usage: ./bridge.sh read <task-id>" && exit 1
        $SSH "cat $BRIDGE/outbox/$2.json 2>/dev/null || echo 'Result not found: $2'"
        ;;
    clear)
        $SSH "rm -f $BRIDGE/outbox/*.json && echo 'Outbox cleared.'"
        ;;
    pull)
        [ -z "$2" ] || [ -z "$3" ] && echo "Usage: ./bridge.sh pull <remote-path> <local-path>" && exit 1
        scp -P "$SSH_PORT" -i "$SSH_KEY" "$SSH_TARGET:$2" "$3"
        ;;
    push)
        [ -z "$2" ] || [ -z "$3" ] && echo "Usage: ./bridge.sh push <local-path> <remote-path>" && exit 1
        scp -P "$SSH_PORT" -i "$SSH_KEY" "$2" "$SSH_TARGET:$3"
        ;;
    worker-start)
        $SSH "nohup $BRIDGE/bridge-worker.sh --watch > $BRIDGE/worker.log 2>&1 &"
        echo "Worker started. Check logs: ./bridge.sh ssh 'tail -f $BRIDGE/worker.log'"
        ;;
    worker-stop)
        $SSH "pkill -f 'bridge-worker.sh --watch' && echo 'Worker stopped.' || echo 'No worker running.'"
        ;;
    worker-status)
        $SSH "pgrep -f bridge-worker.sh > /dev/null && echo 'Worker: RUNNING' || echo 'Worker: STOPPED'; echo \"Pending: \$(ls $BRIDGE/inbox/*.json 2>/dev/null | wc -l)\"; echo \"Completed: \$(ls $BRIDGE/outbox/*.json 2>/dev/null | wc -l)\""
        ;;
    ssh)
        [ -z "$2" ] && echo "Usage: ./bridge.sh ssh <command>" && exit 1
        $SSH "$2"
        ;;
    help|--help|-h)
        usage
        ;;
    *)
        echo "Unknown command: $1"
        usage
        exit 1
        ;;
esac
